### ISSUE TITLE
Container build on release

### ISSUE THREAD

**Issue by lucasew** [AlbughdadiM/satellite-sam-dashboard#1]
To make it easier for people to use this tool you can deploy docker images in the docker registry. It's free for open source projects.

I've done it already with a project [1]. That could be a matter of copying the code and tweaking some options for your case.

That example can be pulled by running `docker pull ghcr.io/lucasew/pocket2kindle/p2k:latest`.

[1] https://github.com/lucasew/pocket2kindle/blob/master/.github/workflows/docker-publish.yml

**Comment by AlbughdadiM** [comment]
Thanks @lucasew  for the suggestion. I've just added the workflow and the image can be pulled 
```bash
docker pull ghcr.io/albughdadim/satellite-sam-dashboard:latest
docker run --name=test -p 8080:8080 satellite-sam-dashboard:latest
```
