### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Rudigithub12345** [AlbughdadiM/satellite-sam-dashboard#2]
Thank you for your incredible work. 
I tried to run satellite sam dashboard in Windows. When I click segment Roi then this error message appear:
Traceback (most recent call last):
  File "rasterio\_io.pyx", line 1450, in rasterio._io.DatasetWriterBase.__init__
  File "rasterio\_err.pyx", line 221, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: Attempt to create new tiff file '/tmp\WOETMTXT.tif' failed: No error

During handling of the above exception, another exception occurred:

rasterio.errors.RasterioIOError: Attempt to create new tiff file '/tmp\WOETMTXT.tif' failed: No error

How to solve it. Thank you.

Rudi

**Comment by AlbughdadiM** [comment]
@Rudigithub12345 could you provide more details on how setup the environment? did you use the dev branch or the prod?
It looks like you have set the dev environment on Windows.I haven't tested that in Windows, but I suspect that it has something to do with the existence of "/tmp" in Windows and how the path is constructed in Windows "/tmp\WOETMTXT.tif" with forward and backward slashes. One work around is to go to config.py and set WORK_DIR to a valid Windows path.
Let me know if this works for you.
