### ISSUE TITLE
Unable to find image 'satellite-sam-dashboard:v0.1' locally

### ISSUE THREAD

**Issue by namakshenas** [AlbughdadiM/satellite-sam-dashboard#4]
Hi, After running the following line:

`docker run --name=dashboard -p 8080:8080 satellite-sam-dashboard:v0.1`

I'm getting this error:

```
Unable to find image 'satellite-sam-dashboard:v0.1' locally
docker: Error response from daemon: pull access denied for satellite-sam-dashboard, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

My system:
MacBook Pro (M2 max)

**Comment by AlbughdadiM** [comment]
Hi @namakshenas 

If you pull the already built image using 

`docker pull ghcr.io/albughdadim/satellite-sam-dashboard:latest`

you can run a container using 

`docker run --name=dashboard -p 8080:8080 ghcr.io/albughdadim/satellite-sam-dashboard:latest`

**Comment by namakshenas** [comment]
I tested and again got the same error!

**Comment by AlbughdadiM** [comment]
Could you provide the full commands that you use to pull the image and build the container along with the error message?

**Comment by namakshenas** [comment]
```
git clone https://github.com/AlbughdadiM/satellite-sam-dashboard.git
cd satellite-sam-dashboard
docker build . -t satellite-sam-dashboard:v0.1
docker run --name=dashboard -p 8080:8080 satellite-sam-dashboard:v0.1
```

and error:
```
Unable to find image 'satellite-sam-dashboard:v0.1' locally
docker: Error response from daemon: pull access denied for satellite-sam-dashboard, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by AlbughdadiM** [comment]
> ```
> 
> git clone https://github.com/AlbughdadiM/satellite-sam-dashboard.git
> 
> cd satellite-sam-dashboard
> 
> docker build . -t satellite-sam-dashboard:v0.1
> 
> docker run --name=dashboard -p 8080:8080 satellite-sam-dashboard:v0.1
> 
> ```
> 
> 
> 
> and error:
> 
> ```
> 
> Unable to find image 'satellite-sam-dashboard:v0.1' locally
> 
> docker: Error response from daemon: pull access denied for satellite-sam-dashboard, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> 
> See 'docker run --help'.
> 
> ```
> 
> 

It looks like you are building the image locally. Probably something went wrong and the built was not successful. If you could provide the logs to the build so I can help with that.
